### ISSUE TITLE
Remove bearer token

### ISSUE THREAD

**Issue by r0mflip** [gnanaswaroop/createathon-iot-demo#1]
Exposed token on [this line](https://github.com/gnanaswaroop/createathon-iot-demo/blob/master/TemperatureRGBSmartLock.ino#L199)

**Comment by gnanaswaroop** [comment]
Thanks removed. Missed that in sanitizing. Anyway, the node name is not posted through and the token itself is not a secret. The method is also not used in this code, only added there as a reference. 

Fixed in #ac277bfdf1061cf268e0faaa050e636e2c8604d1
